### ISSUE TITLE
57 XML beolvasási hiba. cvc-complex-type.

### ISSUE THREAD

**Issue by csuccser** [letscodehu/szamla-agent#16]
Sziasztok! 

A 0.3.1-es verzióban az alábbi hibát kapom ha meghívom a BillingService.createBill(...) függvényt: 

Szamlazz.hu error: 57 XML beolvasási hiba. cvc-complex-type.2.4.a: Invalid content was found starting with element 'nettoErtek'. One of '{"http://www.szamlazz.hu/xmlszamla":afakulcs}' is expected.

Mi erre a megoldás?

**Comment by letscodehu** [comment]
Szia!

A 0.3.4-es verzióban lett javítva az áfakulcsok serializálása, érdemes azzal kipróbálni. Ahol az áfakulcs értéke nem egyezett a TaxCode enum értékeivel ott ilyen hibát eredményezett.

**Comment by csuccser** [comment]
Valóban a TaxCode volt rossz. Azóta már sikerült számlát is generáltatni. 

Köszi a segítséget! :)
